### ISSUE TITLE
Youtube iframe not mobile responsive.

### ISSUE THREAD

**Issue by carloslazo** [opensandiego/opensandiego.github.io#12]
The fixed width of the video iframe in the homepage doesn't scale down to mobile.

<img width="315" alt="screen shot 2019-02-24 at 8 45 29 pm" src="https://user-images.githubusercontent.com/21298082/53314809-25eb0880-3875-11e9-8e05-88deb09c7f8c.png">

**Comment by pigtailz23** [comment]
You can adjust the size in Youtube and replace. I'm not sure if you can make it responsive?

**Comment by nikolajbaer** [comment]
@carloslazo  thanks for making the issue!

I am going to assign this to you. Let me know if you want me to take a look as well.

**Comment by Meggs23** [comment]
I don't know if this is being worked on but the youtube video is showing extra small on the computer version of the home page.

**Comment by nikolajbaer** [comment]
I noticed that too. I will take a look at this (unless @carloslazo you have time), hopefully this week.

**Comment by carloslazo** [comment]
Media queries seem to not be working. I think it's because I didn't upload main.css after running the npm run build command.

Let me know if you think that's the issue.

**Comment by Meggs23** [comment]
That's the only little thing to tidy up that I saw before launching this new site. It looks great! I hope we can launch this week and then futz with the other issues or wanted improvements. :)

**Comment by nikolajbaer** [comment]
Yeah!

I just about have it (and your header font, @Meggs). I am just fixing
alignment on that video and i will push shortly.

**Comment by Meggs23** [comment]
yay! i think y'all have built a solid site and we can play with it more after launch. :)
I also sent you an adjusted home page header on Slack. :)

**Comment by nikolajbaer** [comment]
Ok I just pushed an update with the new header image, new header font, and
cleaned up responsiveness.

Carlos - I found that there is a prefab in Bootstrap that handles the
layout of embeds a bit cleaner, so i subbed out your media queries for it (
i was trying to get the video to nicely fit full frame).

https://getbootstrap.com/docs/4.3/utilities/embed/

**Comment by Meggs23** [comment]
Ooh! I like the new font. Clean with a little texture.
Video looks good on computer and iphone.
I think just the top, blue banner needs something like point it to the volunteer page or something.

Ready to launch! :)
