### ISSUE TITLE
Bad URL in Hyperlink

### ISSUE THREAD

**Issue by jouyoung** [opensandiego/opensandiego.github.io#17]
Hello,

On the main page, the hyperlink "See what kind of things brigades do" to "http://brigade.codeforamerica.org/about/" gives an internal server error. Either "http://brigade.codeforamerica.org/about" or "https://brigade.codeforamerica.org/about" will work.

**Comment by nikolajbaer** [comment]
Interesting, i think we should probably also submit a bug report to brigade.codeforamerica.org, it looks like their "trailing slash" redirect or whatever is not working.
