### ISSUE TITLE
Fix Call-To-Action button spacing on mobile

### ISSUE THREAD

**Issue by appleJax** [opensandiego/opensandiego.github.io#23]
The call-to-action buttons need consistent vertical spacing on mobile.

![Screen Shot 2019-04-02 at 4 20 52 PM](https://user-images.githubusercontent.com/13618860/55442437-7c79ef80-5563-11e9-913a-0cdf13379b1d.png)

**Comment by nikolajbaer** [comment]
Just noting this issue is just on Firefox from my testing.
