### ISSUE TITLE
Change Meetup Widget :hover color

### ISSUE THREAD

**Issue by appleJax** [opensandiego/opensandiego.github.io#24]
Inside the Meetup widget, when the links are hovered, the text turns a shade of blue that is too close to the background color, making it hard to read.

**Event name hovered:**
![Screen Shot 2019-04-02 at 4 24 49 PM](https://user-images.githubusercontent.com/13618860/55442634-59037480-5564-11e9-9ab6-c7b5ab6fd504.png)

**Join button hovered:**
![Screen Shot 2019-04-02 at 4 24 52 PM](https://user-images.githubusercontent.com/13618860/55442639-5d2f9200-5564-11e9-8af5-07c826d257ec.png)

**Comment by evanshulman** [comment]
@appleJax @nikolajbaer Looks like the Meetup Widget is no longer showing? Here's a screenshot from tonight (on Chrome/Mac Chrome/Win10 and Firefox/Mac) along with a screengrab of the Inspect Element for the portion of code I don't think is working. 

<img width="1002" alt="Screen Shot 2019-09-24 at 8 26 45 PM" src="https://user-images.githubusercontent.com/22919684/65567107-d99aa080-df09-11e9-86e2-f19b04691ca7.png">
<img width="801" alt="Screen Shot 2019-09-24 at 8 30 07 PM" src="https://user-images.githubusercontent.com/22919684/65567184-15356a80-df0a-11e9-9036-29391a195ece.png">

**Comment by nikolajbaer** [comment]
Good catch. Quick look it seems like there is something up with the widget
code (backend api change I think). I will see if I can regenerate the embed
code

**Comment by nikolajbaer** [comment]
Meetup widget no longer on homepage.
