### ISSUE TITLE
Update 'about us' page with Steer Co members (to make current for July 2019)

### ISSUE THREAD

**Issue by mwesterfield** [opensandiego/opensandiego.github.io#45]
Update steering co. members on https://opensandiego.org/about page

**Comment by nikolajbaer** [comment]
Current Steerco members:

Jerry Hall | Advisor
-- | --
Isaac Wang | Brigade Captain
Evan | Community Organizer
Marissa | Delivery Lead
Chelsey | Partnerships/Brigade Evangelist, Policy Lead
Eric | Community Data Wrangler/Open Data Evangelist
Tommy | Scribe, Events Lead
Steph | Scribe
Jeffrey | Partnerships/Brigade Evangelist
Nikolaj Baer | Dev Lead/Evangelist | github.com/nikolajbaer | https://linkedin.com/in/nikolajbaer/
Nick | Dev Lead/Evangelist, Scribe

Please update this issue with your Github and LinkedIn information, as well as your last name, or indicate if you do not want to be on the Steer Co list on the website. Thanks!

**Comment by nikolajbaer** [comment]
complete
