### ISSUE TITLE
Establish Style for UI of site

### ISSUE THREAD

**Issue by evanshulman** [opensandiego/opensandiego.github.io#5]
- pick 2 main fonts
- pick color pallette
- main nav styling
- evaluate logo

**Comment by evanshulman** [comment]
will aim to pick from open source fonts (or basically Google Fonts). 
@nikolaj how many Header levels are you using throughout the site? I generally pick one bold, stylish  header font (for like...H1 H2), and then a "easy to read" san serif for body, H3-H5 etc.

color pallette - can go with a "San Diego" colors inspired by the flag/city colors, or with a CfA color set (i.e. Red), or with the current logo soft green/blue and build off of that (for now).

**Comment by pigtailz23** [comment]
Logo done.
Color palette done... using CFA brand guidelines.
Main nav styling done.
Fonts: still working.

**Comment by evanshulman** [comment]
@Meggs23 just confirming you're working with the Google Fonts library (https://fonts.google.com/), or whatever fonts you end up picking, it's easy (and legal :) )for @nikolajbaer to install on our server to use.

**Comment by Meggs23** [comment]
I asked @nikolajbaer about it. It seemed like there were a lot of things on the plate so I didn't push it. I can ask again. :)

**Comment by nikolajbaer** [comment]
Hi there, i can get the fonts in there. Let me know which fonts you want
for the headers and body copy.

**Comment by Meggs23** [comment]
Hi! If you have time, I thought Roboto Slab for the headers... https://fonts.google.com/specimen/Roboto+Slab?selection.family=Roboto+Slab

**Comment by nikolajbaer** [comment]
Roboto Slab is now up on the headers, and we have the color palette for the primary buttons. 

If this is good for now, i will close this, and we can open up a new issue with future changes (i prefer to keep issues from dragging out too long).

**Comment by evanshulman** [comment]
LGTM - we can likely close out. 

My only further opinions/perspectives for styling at this moment are:
- **Can we alter the Twitter widget?** It's default text seems to be different than our page (I show our body text font as "system-ui"). Would be great if we could align to our page. Or at least put a Twitter blue border around it, so it matches the Meetup widget as a separate widget.
- **Can we alter the Meetup widget?** Make the Meeting Name in Roboto Slab, but then the "Join" button and other info text the same font as our body font?
- **Can we add more whitespace to our margins/padding?** In my opinion and experience, more whitespace/negative space helps create a more open feeling and a more "breathable" page when content isn't too close to each other. As it is now, to my eye/feeling, content/text is too close to each other which creates a "bunched up" feeling. 
-- possible options: make the margin 24 from 8 for the h2 class display-4? I'd have to play around with spacing to provide more specific numbers, but if it's easy, I'd recommend boosting margins/padding to around that much for now.

**Comment by evanshulman** [comment]
I'll split my previous comments out into separate issue/tickets and post here when I create them out, per convo with @nikolajbaer

**Comment by nikolajbaer** [comment]
Closing this for now. Maybe new style changes can be created as new specific issues (per @evanshulman )
