### ISSUE TITLE
Add Voter's Voice Dashboard to Project List / Featured Projects

### ISSUE THREAD

**Issue by nikolajbaer** [opensandiego/opensandiego.github.io#65]
**Describe the feature briefly:**
Quick Synopsis and partners would be great

**What needs to be done?**
Add a project in the _projects folder (just crib off the other projects).

**Where does this appear?**
Homepage and projects page

**Comment by nikolajbaer** [comment]
@tommy-stone if you have a quick synopsis written somewhere, paste it in here and I can put it up pretty quick!

**Comment by tommy-stone** [comment]
Discussed with Daniel who will be working on the project. Sent summary with information

**Comment by tommy-stone** [comment]
This was resolved on commit f3af02c3229b8d8982054a529f9e4f2bd5acafff
