### ISSUE TITLE
Remove multiple buttons on homepage hero image

### ISSUE THREAD

**Issue by kristinbpowers** [opensandiego/opensandiego.github.io#97]
If we haven't picked what's going to get the boot, we can talk about that...but having three is too much. I personally wouldn't mind it being one "Learn More" button that takes people to the "Get Involved" page where the links to join us on Meetup, Slack, etc are listed.

**Comment by nikolajbaer** [comment]
Completed with PR https://github.com/opensandiego/opensandiego.github.io/pull/95
